services:
  - type: web
    name: bigpump-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
